### ISSUE TITLE
Eloquent patch release

### ISSUE THREAD

**Issue by dirk-thomas** [ament/ament_package#109]
I propose to sync the `eloquent` branch with `master` which will backport #106, #107, and #108 and then release 0.8.6 into Eloquent (also `--ff-only` that release to the `master` branch). That will allow both branches to stay in sync.

**Comment by dirk-thomas** [comment]
@mjcarroll Can you "approve" this?

**Comment by mjcarroll** [comment]
Yes, let's do it :+1:

**Comment by dirk-thomas** [comment]
Done: ros/rosdistro#23218.
