### ISSUE TITLE
what error

### ISSUE THREAD

**Issue by Autostone-c** [ament/ament_package#142]
nvidia@nvidianvidia:/data/autoware$ source install/setup.bash
-bash: ament_prepend_unique_value: command not found

I have two sets of ROS2 source code, each in a different path, and one set of autoware. When I source, the following errors occur

**Comment by clalancette** [comment]
Please open questions like this on https://answers.ros.org, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
