### ISSUE TITLE
Repository description seems inaccurate

### ISSUE THREAD

**Issue by scpeters** [ament/ament_package#144]
The repository description that shows on the right side of the homepage seems inaccurate:

> Python package for parsing package manifest files (package.xml).

I looked through the code and don't see any python code for parsing package.xml files in this repository. Looking elsewhere, the [ament_package_xml.cmake](https://github.com/ament/ament_cmake/blob/rolling/ament_cmake_core/cmake/core/ament_package_xml.cmake) code in ament_cmake invokes its [package_xml_2_cmake.py](https://github.com/ament/ament_cmake/blob/rolling/ament_cmake_core/cmake/core/package_xml_2_cmake.py#L22) script, and it uses [`parse_package_string` from `catkin_pkg.package`](https://github.com/ament/ament_cmake/blob/rolling/ament_cmake_core/cmake/core/package_xml_2_cmake.py#L22).

**Comment by sloretz** [comment]
The description of the repository does seem to be incorrect. AFAIK `catkin_pkg` is the official package.xml parsing package.

This repository houses templates for shell scripts used to create an ament workspace. They are used by [ament_cmake](https://github.com/ament/ament_cmake) and [ros_workspace](https://github.com/ros2/ros_workspace). These are the scripts that get run when you source a debian installed ROS workspace `. /opt/ros/rolling/setup.bash` etc. There are two kinds of scripts

* package - if you `cmake && make install` an individual package using ament_cmake it installs shell scripts you can source to use that package
* workspace  (aka prefix_level) - when you install any ROS debian package the main `. /opt/ros/rolling/setup.bash` is a "prefix level" script that tries to source all the package level scripts it can find.

Note this is different from colcon workspaces. When you build a workspace with colcon it installs its own shell scripts to make the packages useful.

How about changing the description to  `Contains shell script templates used to create ament workspaces.`?

**Comment by clalancette** [comment]
> How about changing the description to `Contains shell script templates used to create ament workspaces.`?

I shortened it to `Shell script templates used to create ament workspaces.`, and applied it to the repository.

With that, I'm going to close this out.  @scpeters thanks for bringing it up, and @sloretz thanks for the wording.
