### ISSUE TITLE
`.dsv` files are not processed unless there is `.sh` file with the same base name

### ISSUE THREAD

**Issue by azeey** [ament/ament_package#145]
When using `ament_environment_hooks`, `.dsv` files not processed properly unless there is a `.sh` file with the same name registered with `ament_environment_hooks`. This `.sh` file can be an empty file.

The issue appears to be with `ament_package` since building this package with `colcon` doesn't exhibit the same problem.

MWE: https://github.com/azeey/sandbox/tree/master/test_ament_pkg

It seems like https://github.com/ament/ament_package/blob/35b15ae4d8c5e1dbb6ab622ff95d046aa3ca1b28/ament_package/template/prefix_level/_local_setup_util.py#L257 only processes files with `primary_extension` or `additional_extension`, which in my system were `.sh` and `.zsh`, so `.dsv` files seem to be ignored.

Potential fix (works for me locally):

```diff
diff --git a/ament_package/template/prefix_level/_local_setup_util.py b/ament_package/template/prefix_level/_local_setup_util.py
index fe2afda..29849f3 100644
--- a/ament_package/template/prefix_level/_local_setup_util.py
+++ b/ament_package/template/prefix_level/_local_setup_util.py
@@ -254,7 +254,7 @@ def process_dsv_file(
             path_without_ext, ext = os.path.splitext(remainder)
             assert ext.startswith('.')
             ext = ext[1:]
-            if ext in (primary_extension, additional_extension):
+            if ext in (primary_extension, additional_extension, 'dsv'):
                 if path_without_ext not in basenames:
                     basenames[path_without_ext] = set()
                 basenames[path_without_ext].add(ext)
```

**Comment by sloretz** [comment]
I'm not totally sure what's happening yet, but from some debugging with `set -x` before sourcing a colcon workspace I see colcon's `_local_setup_util_sh.py` alone finds the dsv file

```
++++ /usr/bin/python3 /workspaces/ament_package_145/install/_local_setup_util_sh.py sh
+++ _colcon_ordered_commands='export CMAKE_PREFIX_PATH="/workspaces/ament_package_145/install/test_ament_pkg:$CMAKE_PREFIX_PATH"
export AMENT_PREFIX_PATH="/workspaces/ament_package_145/install/test_ament_pkg:$AMENT_PREFIX_PATH"
export HAVE_TEST_HOOK="It works!"
```

I also see `ament_package` has a subtle difference with colcon's generated python util file in the same area where you made a change. ament_package sets `basenames[path_without_ext]` only if the extension is known.

https://github.com/ament/ament_package/blob/35b15ae4d8c5e1dbb6ab622ff95d046aa3ca1b28/ament_package/template/prefix_level/_local_setup_util.py#L252-L260

vs colcon always sets `basenames[path_without_ext]` to an empty `set()`.

```
        else:
            # group remaining source lines by basename
            path_without_ext, ext = os.path.splitext(remainder)
            if path_without_ext not in basenames:
                basenames[path_without_ext] = set()
            assert ext.startswith('.')
            ext = ext[1:]
            if ext in (primary_extension, additional_extension):
                basenames[path_without_ext].add(ext)
```

I suspect that makes all the difference here because that causes the `for` loop below to be entered, but I'm not sure whether `ament_package` or `colcon` is more correct yet.

**Comment by sloretz** [comment]
Ok, I'm going to go with `colcon` is more correct because this change appears intentional: https://github.com/colcon/colcon-core/commit/5a293a82e151473b77364bbd7b2f730f674eb7c2

I think the right fix here is to port that change to `ament/ament_package`. @azeey would you be willing to open a PR?

**Comment by azeey** [comment]
> Ok, I'm going to go with `colcon` is more correct because this change appears intentional: [colcon/colcon-core@5a293a8](https://github.com/colcon/colcon-core/commit/5a293a82e151473b77364bbd7b2f730f674eb7c2) ([colcon/colcon-core#244](https://github.com/colcon/colcon-core/pull/244))
> 
> I think the right fix here is to port that change to `ament/ament_package`. @azeey would you be willing to open a PR?

Yup. https://github.com/ament/ament_package/pull/147
