### ISSUE TITLE
ament build fails

### ISSUE THREAD

**Issue by Karsten1987** [ament/ament_package#42]
error msg:

```
Traceback (most recent call last):
  File "src/ament/ament_tools/scripts/ament.py", line 37, in <module>
    import ament_package
  File "/home/karsten/workspace/osrf/ros2_src/src/ament/ament_package/ament_package/__init__.py", line 83
    def parse_package_string(data, *, filename=None):
                                    ^
SyntaxError: invalid syntax
```

am I doing something wrong here?

**Comment by dirk-thomas** [comment]
What Python version are you using? Our code base requires 3.5.

This specific syntax enforces that keyword arguments are not being passed as positional arguments and is not valid in older Python versions.

**Comment by dhood** [comment]
closed with https://github.com/ament/ament_tools/pull/106
