### ISSUE TITLE
Not enforcing ROS name convention when building NON-ROS packages

### ISSUE THREAD

**Issue by barbalberto** [ament/ament_package#47]
Hi guys, thans a lot for your hard work in building ament tool. I'm not sure this is the right place for the issue/request, if not please point me to the right place.

My request is quite simple, I'm experimenting ament as a build system for my project, in which I have both ROS and NON-ROS packages.
 I have an increasing number of repos (30 or so) and **I'd love to use ament as my build system**.

My problem is that some of my NON-ROS packages do not comply with ROS naming conventions and, while `catkin` was complaining but still going on, `ament` is enforcing the name convention therefore it quits immediatly.

I know this may be outside the scope of ament development, but would it be possible to have a way to skip this check for non-ROS packages?
For example by inserting a tag in the package.xml file? Or by setting a different built_type, something like:
```
  <export>
    <build_type> cmake </build_type>
  </export>
```

It'll be really appreciate because I'm looking for a cross platform build system and this looks really promising.

**Comment by dirk-thomas** [comment]
Thank you for bringing this issue up. It is good to hear that the tool is being useful to you outside the scope of ROS. I would be happy to adapt `ament` to support this use case. Can you please clarify which part is currently to strict for your non-ROS packages. Is it the package name (https://github.com/ament/ament_package/blob/master/ament_package/package.py#L101-L102) or something else?

**Comment by barbalberto** [comment]
Thanks you @dirk-thomas for your reply.
Up to now I found the following points
- The one you mention in package.py
- Function `extract_project_name` from https://github.com/ament/ament_tools/blob/master/ament_tools/package_types/cmake.py#L84
- I guess also the subsequent function `extract_build_dependencies` will have the same behaviour when a package has a non-ros dependency https://github.com/ament/ament_tools/blob/master/ament_tools/package_types/cmake.py#L98

The characters I'd like to be allowed are capital letters and the hyphen sign `-` 
I'm fine with the starting character should be an alphabetic one, also capitals should be allowed as starter.

Little extra note:
The function `extract_project_name` fails when the CMake `Project()` function uses a variable, like:
```
set(MY_NAME  foo)
project(${MY_NAME})
```
That's not a big deal, CMakeFiles can be fixed to adapt to it.
It fails also if the command `Project()` is totally missing, which I think it is good. I was wandering if a specific error message could help the user to identify this error and fix it.

**Comment by dirk-thomas** [comment]
For now it is probably best for you to comment out / relax these checks to make it work for your use cases. I can hopefully provide you with a better alternative in the future.

Just for context why ROS limits the valid names:
* When you want to release a package as e.g. a Debian package you are restricted to names with lower cases and only have the `-` separator available. If we would allow mixed cases and also underscores we could end up with two packages (e.g. `foo-bar` and `Foo_Bar`) which are when being transformed into compliant Debian package names identical and therefore not both releasable. But I understand why the tool should be restricting your choices when you only want to build from source.

The "introspection" of the CMake project name is indeed not able to interpret CMake logic. Only string literals can be read. If you can update your CMake file to comply that is fine for now. In the future I expect you to be able to provide that additional information (the package name if not inferable from looking at the CMake files) through external configuration.

**Comment by barbalberto** [comment]
> For now it is probably best for you to comment out / relax these checks to make it work for your use cases. I can hopefully provide you with a better alternative in the future.

I'll made a personal fork to share with my coworker, and maybe try something out there.

Thanks for explaining the reason of this limitation. Right now we change the name in the process of building the Debian package, but I agree that starting with the right name from the beginning it is better.
A question: is catkin/ament able to build the .deb itself or do you use a different tool for this process?

> The "introspection" of the CMake project name is indeed not able to interpret CMake logic

Yes, sorry, the note was not meant to be a bug 

> In the future I expect you to be able to provide that additional information (the package name if not inferable from looking at the CMake files) through external configuration.

Can you tell me more about this? With external configuration you mean the package.xml or something else?
I was also looking for a way to call CMake with some flags, like you do from command line with: `cmake -DFoo=bar ..` or with `cmake -C <initial-cache> ..`

**Comment by dirk-thomas** [comment]
> A question: is catkin/ament able to build the .deb itself or do you use a different tool for this process?

Neither of these tools can build a Debian package. In ROS we use the tool `bloom` to generate the necessary files for proper Debian packages. The build farm later calls `apt-src build` to make a package out of it.

But you can use other existing "standard" tools like `dpkg-buildpackage` on the install space of a catkin / ament workspace. 


> > In the future I expect you to be able to provide that additional information (the package name if not inferable from looking at the CMake files) through external configuration.

> Can you tell me more about this?

There is not yet much to share. It is a small side project I am working on. Once I have something useful for others I can post a link here.

> With external configuration you mean the package.xml or something else?

The ROS package manifest comes with many constraints due to it being used to also provide enough information for packaging. The tool should allow you to also process packages which don't have such a file. Missing information should then be possible to be provided through an external source (e.g. a yaml file in the workspace). This is especially relevant if you don't control the sources and upstream doesn't want to add a file like the package.xml.  


> I was also looking for a way to call CMake with some flags, like you do from command line with: `cmake -DFoo=bar ..` or with `cmake -C <initial-cache> ..`

`ament_tools build` has an command line option to pass arbitrary CMake args. But currently those are passed to all packages in a workspace. In order to specify package specific arguments you currently have to split up your workspace.

**Comment by barbalberto** [comment]
> The tool should allow you to also process packages which don't have such a file. Missing information should then be possible to be provided through an external source (e.g. a yaml file in the workspace). This is especially relevant if you don't control the sources and upstream doesn't want to add a file like the package.xml.

Really good point. I agree.
Thank you so much for all this precious information. Hope to keep in touch with you.

**Comment by audrow** [comment]
I'm not sure this is still relevant, so I'm going to close this issue. Feel free to open it back up if there is renewed interest in this.
