### ISSUE TITLE
Convert prefix level setup.bat file to batch

### ISSUE THREAD

**Issue by wjwwood** [ament/ament_package#8]
The prefix level `setup.bat` file was never converted from shell to batch.

AC:

- [x] Workspace chaining works by calling the `setup.bat` of the second workspace on Windows

**Comment by wjwwood** [comment]
https://github.com/ament/ament_package/pull/6#issue-60469101

**Comment by dirk-thomas** [comment]
Confirmed to work with ament/ament_package#22.
