### ISSUE TITLE
local_setup.bat fails if PYTHON_EXECUTABLE contains parentheses

### ISSUE THREAD

**Issue by cottsay** [ament/ament_package#84]
Evidently parentheses need to be escaped with `^` when used in a `for /f`, even if double-quoted. Without this fix, I get messages like:
```
/Microsoft was unexpected at this time.
```

Workaround is to modify the generated `local_setup.bat` and escape the parentheses with carats like this:
```
...
  set "ament_python_executable=C:/Program Files ^(x86^)/Microsoft Visual Studio/Shared/Python37_64/python.exe"
...
```

**Comment by dirk-thomas** [comment]
Can you post the complete `local_setup.bat` file which causes the problem.

**Comment by cottsay** [comment]
This is the exact spot that causes the problem:
https://github.com/ament/ament_package/blob/688d7ffa1a32524aaa8a07e3929f93150e959422/ament_package/template/prefix_level/local_setup.bat.in#L26

**Comment by dirk-thomas** [comment]
> This is the exact spot that causes the problem:
https://github.com/ament/ament_package/blob/688d7ffa1a32524aaa8a07e3929f93150e959422/ament_package/template/prefix_level/local_setup.bat.in#L26

I doubt that this exact line is causing the problem. You can successfully set any kind of value as long as it is quoted like this: try `set "FOO=bar (baz)"`. So I suspect the problem happens later.

**Comment by cottsay** [comment]
> I doubt that this exact line is causing the problem.

You're right, I updated my comment with the correct location. The line I referenced was where the workaround was made.

**Comment by dirk-thomas** [comment]
Can you try to insert the following line after the `set` line:

```
set "ament_python_executable=%ament_python_executable:)=^)%"
```

**Comment by cottsay** [comment]
> Can you try to insert the following line after the `set` line:
> 
> ```
> set "ament_python_executable=%ament_python_executable:)=^)%"
> ```

I no longer get an error after inserting that line. Looks like only the closing parentheses is escaped - is that intentional?

**Comment by dirk-thomas** [comment]
Yes, that should to be sufficient - I assume otherwise it considers it to be the end of the for loop parenthesis.
